# Generated by Django 2.1.5 on 2019-02-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=2500, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('points', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('region_1', models.CharField(max_length=100, null=True)),
                ('region_2', models.CharField(max_length=100, null=True)),
                ('variety', models.CharField(max_length=100, null=True)),
                ('winery', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
